@draft @portable @calendar @weekday @reference-dm700
Feature: Gregorian year types and supported boundaries
  These rows freeze one numeric weekday result or one public failure for each original request.
  Arithmetic-input diagnostics are portable categories; native warning and exception text is excluded.

  Background:
    Given each case starts in a fresh process and temporary working directory
    And the timezone is UTC, the language is English, and the locale is C UTF-8
    And the functional profiles use reference clock 2040-02-28 10:20:30 UTC
    And weekday 1 means Monday through weekday 7 meaning Sunday
    And a named civil date has fields year, month, and day
    And the profiles are defined exactly as follows:
      | profile | behavior version | public input shape | full-year domain | default short-year rule | clock setting |
      | calendar-service | 7.00 | one ordered collection of year, month, day | 0001 through 9999 | not applicable | none because weekday arithmetic has no clock input |
      | current-functional | 7.00 | separate month, day, year fields | 0001 through 9999 | 89 | 2040-02-28 10:20:30 UTC |
      | legacy-functional | 5.66 from distribution 7.00 | separate month, day, year fields | 0001 through 9999 | 89 | 2040-02-28 10:20:30 UTC |

  Scenario Outline: Observe one weekday request
    Given I select profile <profile>
    When I request weekdays with <request>
    Then the ordered public outcomes are <result>

    Examples:
      | case | profile | request | result |
      | WD-P2-TYPE-BASE-COMMON-JAN1-1 | calendar-service | {"year_type":"common","january_1_weekday":1,"civil_dates":[{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1},{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-2 | calendar-service | {"year_type":"common","january_1_weekday":2,"civil_dates":[{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1},{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-3 | calendar-service | {"year_type":"common","january_1_weekday":3,"civil_dates":[{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1},{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-4 | calendar-service | {"year_type":"common","january_1_weekday":4,"civil_dates":[{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1},{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-5 | calendar-service | {"year_type":"common","january_1_weekday":5,"civil_dates":[{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1},{"year":2010,"month":12,"day":31},{"year":2011,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-6 | calendar-service | {"year_type":"common","january_1_weekday":6,"civil_dates":[{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1},{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-COMMON-JAN1-7 | calendar-service | {"year_type":"common","january_1_weekday":7,"civil_dates":[{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1},{"year":2006,"month":12,"day":31},{"year":2007,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-1 | calendar-service | {"year_type":"leap","january_1_weekday":1,"civil_dates":[{"year":2023,"month":12,"day":31},{"year":2024,"month":1,"day":1},{"year":2024,"month":12,"day":31},{"year":2025,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-2 | calendar-service | {"year_type":"leap","january_1_weekday":2,"civil_dates":[{"year":2007,"month":12,"day":31},{"year":2008,"month":1,"day":1},{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-3 | calendar-service | {"year_type":"leap","january_1_weekday":3,"civil_dates":[{"year":2019,"month":12,"day":31},{"year":2020,"month":1,"day":1},{"year":2020,"month":12,"day":31},{"year":2021,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-4 | calendar-service | {"year_type":"leap","january_1_weekday":4,"civil_dates":[{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1},{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-5 | calendar-service | {"year_type":"leap","january_1_weekday":5,"civil_dates":[{"year":2015,"month":12,"day":31},{"year":2016,"month":1,"day":1},{"year":2016,"month":12,"day":31},{"year":2017,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-6 | calendar-service | {"year_type":"leap","january_1_weekday":6,"civil_dates":[{"year":1999,"month":12,"day":31},{"year":2000,"month":1,"day":1},{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-BASE-LEAP-JAN1-7 | calendar-service | {"year_type":"leap","january_1_weekday":7,"civil_dates":[{"year":2011,"month":12,"day":31},{"year":2012,"month":1,"day":1},{"year":2012,"month":12,"day":31},{"year":2013,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-1 | current-functional | {"year_type":"common","january_1_weekday":1,"civil_dates":[{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1},{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-2 | current-functional | {"year_type":"common","january_1_weekday":2,"civil_dates":[{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1},{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-3 | current-functional | {"year_type":"common","january_1_weekday":3,"civil_dates":[{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1},{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-4 | current-functional | {"year_type":"common","january_1_weekday":4,"civil_dates":[{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1},{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-5 | current-functional | {"year_type":"common","january_1_weekday":5,"civil_dates":[{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1},{"year":2010,"month":12,"day":31},{"year":2011,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-6 | current-functional | {"year_type":"common","january_1_weekday":6,"civil_dates":[{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1},{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-COMMON-JAN1-7 | current-functional | {"year_type":"common","january_1_weekday":7,"civil_dates":[{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1},{"year":2006,"month":12,"day":31},{"year":2007,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-1 | current-functional | {"year_type":"leap","january_1_weekday":1,"civil_dates":[{"year":2023,"month":12,"day":31},{"year":2024,"month":1,"day":1},{"year":2024,"month":12,"day":31},{"year":2025,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-2 | current-functional | {"year_type":"leap","january_1_weekday":2,"civil_dates":[{"year":2007,"month":12,"day":31},{"year":2008,"month":1,"day":1},{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-3 | current-functional | {"year_type":"leap","january_1_weekday":3,"civil_dates":[{"year":2019,"month":12,"day":31},{"year":2020,"month":1,"day":1},{"year":2020,"month":12,"day":31},{"year":2021,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-4 | current-functional | {"year_type":"leap","january_1_weekday":4,"civil_dates":[{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1},{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-5 | current-functional | {"year_type":"leap","january_1_weekday":5,"civil_dates":[{"year":2015,"month":12,"day":31},{"year":2016,"month":1,"day":1},{"year":2016,"month":12,"day":31},{"year":2017,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-6 | current-functional | {"year_type":"leap","january_1_weekday":6,"civil_dates":[{"year":1999,"month":12,"day":31},{"year":2000,"month":1,"day":1},{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM6-LEAP-JAN1-7 | current-functional | {"year_type":"leap","january_1_weekday":7,"civil_dates":[{"year":2011,"month":12,"day":31},{"year":2012,"month":1,"day":1},{"year":2012,"month":12,"day":31},{"year":2013,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-1 | legacy-functional | {"year_type":"common","january_1_weekday":1,"civil_dates":[{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1},{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-2 | legacy-functional | {"year_type":"common","january_1_weekday":2,"civil_dates":[{"year":2001,"month":12,"day":31},{"year":2002,"month":1,"day":1},{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-3 | legacy-functional | {"year_type":"common","january_1_weekday":3,"civil_dates":[{"year":2002,"month":12,"day":31},{"year":2003,"month":1,"day":1},{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-4 | legacy-functional | {"year_type":"common","january_1_weekday":4,"civil_dates":[{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1},{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-5 | legacy-functional | {"year_type":"common","january_1_weekday":5,"civil_dates":[{"year":2009,"month":12,"day":31},{"year":2010,"month":1,"day":1},{"year":2010,"month":12,"day":31},{"year":2011,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-6 | legacy-functional | {"year_type":"common","january_1_weekday":6,"civil_dates":[{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1},{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-COMMON-JAN1-7 | legacy-functional | {"year_type":"common","january_1_weekday":7,"civil_dates":[{"year":2005,"month":12,"day":31},{"year":2006,"month":1,"day":1},{"year":2006,"month":12,"day":31},{"year":2007,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-1 | legacy-functional | {"year_type":"leap","january_1_weekday":1,"civil_dates":[{"year":2023,"month":12,"day":31},{"year":2024,"month":1,"day":1},{"year":2024,"month":12,"day":31},{"year":2025,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-2 | legacy-functional | {"year_type":"leap","january_1_weekday":2,"civil_dates":[{"year":2007,"month":12,"day":31},{"year":2008,"month":1,"day":1},{"year":2008,"month":12,"day":31},{"year":2009,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-3 | legacy-functional | {"year_type":"leap","january_1_weekday":3,"civil_dates":[{"year":2019,"month":12,"day":31},{"year":2020,"month":1,"day":1},{"year":2020,"month":12,"day":31},{"year":2021,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-4 | legacy-functional | {"year_type":"leap","january_1_weekday":4,"civil_dates":[{"year":2003,"month":12,"day":31},{"year":2004,"month":1,"day":1},{"year":2004,"month":12,"day":31},{"year":2005,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-5 | legacy-functional | {"year_type":"leap","january_1_weekday":5,"civil_dates":[{"year":2015,"month":12,"day":31},{"year":2016,"month":1,"day":1},{"year":2016,"month":12,"day":31},{"year":2017,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-6 | legacy-functional | {"year_type":"leap","january_1_weekday":6,"civil_dates":[{"year":1999,"month":12,"day":31},{"year":2000,"month":1,"day":1},{"year":2000,"month":12,"day":31},{"year":2001,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-TYPE-DM5-LEAP-JAN1-7 | legacy-functional | {"year_type":"leap","january_1_weekday":7,"civil_dates":[{"year":2011,"month":12,"day":31},{"year":2012,"month":1,"day":1},{"year":2012,"month":12,"day":31},{"year":2013,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-LOWER-ENDPOINT | calendar-service | {"control":"lower endpoint","civil_dates":[{"year":1,"month":1,"day":1},{"year":1,"month":12,"day":31},{"year":2,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-EARLY-LEAP | calendar-service | {"control":"early leap","civil_dates":[{"year":4,"month":2,"day":28},{"year":4,"month":2,"day":29},{"year":4,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-CENTURY-1900 | calendar-service | {"control":"century 1900","civil_dates":[{"year":1900,"month":2,"day":28},{"year":1900,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-CENTURY-2000 | calendar-service | {"control":"century 2000","civil_dates":[{"year":2000,"month":2,"day":28},{"year":2000,"month":2,"day":29},{"year":2000,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-CENTURY-2100 | calendar-service | {"control":"century 2100","civil_dates":[{"year":2100,"month":2,"day":28},{"year":2100,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-CENTURY-2400 | calendar-service | {"control":"century 2400","civil_dates":[{"year":2400,"month":2,"day":28},{"year":2400,"month":2,"day":29},{"year":2400,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-UPPER-ENDPOINT | calendar-service | {"control":"upper endpoint","civil_dates":[{"year":9998,"month":12,"day":31},{"year":9999,"month":1,"day":1},{"year":9999,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-BASE-NUMERIC-YEAR-40 | calendar-service | {"control":"numeric year 40","civil_dates":[{"year":40,"month":1,"day":1},{"year":40,"month":2,"day":29},{"year":40,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-LOWER-ENDPOINT | current-functional | {"control":"lower endpoint","civil_dates":[{"year":1,"month":1,"day":1},{"year":1,"month":12,"day":31},{"year":2,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-EARLY-LEAP | current-functional | {"control":"early leap","civil_dates":[{"year":4,"month":2,"day":28},{"year":4,"month":2,"day":29},{"year":4,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-CENTURY-1900 | current-functional | {"control":"century 1900","civil_dates":[{"year":1900,"month":2,"day":28},{"year":1900,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-CENTURY-2000 | current-functional | {"control":"century 2000","civil_dates":[{"year":2000,"month":2,"day":28},{"year":2000,"month":2,"day":29},{"year":2000,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-CENTURY-2100 | current-functional | {"control":"century 2100","civil_dates":[{"year":2100,"month":2,"day":28},{"year":2100,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-CENTURY-2400 | current-functional | {"control":"century 2400","civil_dates":[{"year":2400,"month":2,"day":28},{"year":2400,"month":2,"day":29},{"year":2400,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-UPPER-ENDPOINT | current-functional | {"control":"upper endpoint","civil_dates":[{"year":9998,"month":12,"day":31},{"year":9999,"month":1,"day":1},{"year":9999,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM6-NUMERIC-YEAR-40 | current-functional | {"control":"numeric year 40","civil_dates":[{"year":40,"month":1,"day":1},{"year":40,"month":2,"day":29},{"year":40,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-LOWER-ENDPOINT | legacy-functional | {"control":"lower endpoint","civil_dates":[{"year":1,"month":1,"day":1},{"year":1,"month":12,"day":31},{"year":2,"month":1,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-EARLY-LEAP | legacy-functional | {"control":"early leap","civil_dates":[{"year":4,"month":2,"day":28},{"year":4,"month":2,"day":29},{"year":4,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"},{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-CENTURY-1900 | legacy-functional | {"control":"century 1900","civil_dates":[{"year":1900,"month":2,"day":28},{"year":1900,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-CENTURY-2000 | legacy-functional | {"control":"century 2000","civil_dates":[{"year":2000,"month":2,"day":28},{"year":2000,"month":2,"day":29},{"year":2000,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-CENTURY-2100 | legacy-functional | {"control":"century 2100","civil_dates":[{"year":2100,"month":2,"day":28},{"year":2100,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-CENTURY-2400 | legacy-functional | {"control":"century 2400","civil_dates":[{"year":2400,"month":2,"day":28},{"year":2400,"month":2,"day":29},{"year":2400,"month":3,"day":1}]} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"},{"status":"completed","weekday":2,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-UPPER-ENDPOINT | legacy-functional | {"control":"upper endpoint","civil_dates":[{"year":9998,"month":12,"day":31},{"year":9999,"month":1,"day":1},{"year":9999,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"},{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P2-CONTROL-DM5-NUMERIC-YEAR-40 | legacy-functional | {"control":"numeric year 40","civil_dates":[{"year":40,"month":1,"day":1},{"year":40,"month":2,"day":29},{"year":40,"month":12,"day":31}]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"},{"status":"completed","weekday":3,"diagnostic":"none"},{"status":"completed","weekday":1,"diagnostic":"none"}]} |
