@draft @portable @calendar @weekday @reference-dm700
Feature: Malformed weekday inputs and short years
  These rows freeze one numeric weekday result or one public failure for each original request.
  Arithmetic-input diagnostics are portable categories; native warning and exception text is excluded.

  Background:
    Given each case starts in a fresh process and temporary working directory
    And the timezone is UTC, the language is English, and the locale is C UTF-8
    And the functional profiles use reference clock 2040-02-28 10:20:30 UTC
    And weekday 1 means Monday through weekday 7 meaning Sunday
    And a named civil date has fields year, month, and day
    And the profiles are defined exactly as follows:
      | profile | behavior version | public input shape | full-year domain | default short-year rule | clock setting |
      | calendar-service | 7.00 | one ordered collection of year, month, day | 0001 through 9999 | not applicable | none because weekday arithmetic has no clock input |
      | current-functional | 7.00 | separate month, day, year fields | 0001 through 9999 | 89 | 2040-02-28 10:20:30 UTC |
      | legacy-functional | 5.66 from distribution 7.00 | separate month, day, year fields | 0001 through 9999 | 89 | 2040-02-28 10:20:30 UTC |

  Scenario Outline: Observe one weekday request
    Given I select profile <profile>
    When I request weekdays with <request>
    Then the ordered public outcomes are <result>

    Examples:
      | case | profile | request | result |
      | WD-P3-FIELD-BASE-MONTH-ZERO | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":0},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-MONTH-13 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":13},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-MONTH-NEG1 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":-1},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-MONTH-FRACTION | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1.5},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-DAY-ZERO | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":0}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-DAY-NEG1 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":-1}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-DAY-32 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":32}}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-DAY-FRACTION | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":1.5}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-COMMON-FEB29 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2041},"month":{"type":"number","value":2},"day":{"type":"number","value":29}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-LEAP-FEB30 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":2},"day":{"type":"number","value":30}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-APRIL31 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":4},"day":{"type":"number","value":31}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-YEAR-ZERO | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":0},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-YEAR-NEG1 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":-1},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-YEAR-10000 | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":10000},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-YEAR-FRACTION | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040.5},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-BASE-YEAR-EMPTY | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"empty-text"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-MONTH-EMPTY | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"empty-text"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-DAY-EMPTY | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"empty-text"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-YEAR-NONNUMERIC | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"text","value":"year"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-MONTH-NONNUMERIC | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"text","value":"month"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-DAY-NONNUMERIC | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"text","value":"day"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-YEAR-ABSENT | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"absent"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-MONTH-ABSENT | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"absent"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-BASE-DAY-ABSENT | calendar-service | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"absent"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-MONTH-ZERO | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":0},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-MONTH-13 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":13},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-MONTH-NEG1 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":-1},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-MONTH-FRACTION | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1.5},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-DAY-ZERO | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":0}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-DAY-NEG1 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":-1}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-DAY-32 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":32}}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-DAY-FRACTION | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":1.5}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-COMMON-FEB29 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2041},"month":{"type":"number","value":2},"day":{"type":"number","value":29}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-LEAP-FEB30 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":2},"day":{"type":"number","value":30}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-APRIL31 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":4},"day":{"type":"number","value":31}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-YEAR-ZERO | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":0},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-YEAR-NEG1 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":-1},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-YEAR-10000 | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":10000},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-YEAR-FRACTION | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040.5},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM6-YEAR-EMPTY | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"empty-text"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-MONTH-EMPTY | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"empty-text"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-DAY-EMPTY | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"empty-text"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-YEAR-NONNUMERIC | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"text","value":"year"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-MONTH-NONNUMERIC | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"text","value":"month"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-DAY-NONNUMERIC | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"text","value":"day"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-YEAR-ABSENT | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"absent"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-MONTH-ABSENT | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"absent"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM6-DAY-ABSENT | current-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"absent"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-MONTH-ZERO | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":0},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-MONTH-13 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":13},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-MONTH-NEG1 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":-1},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-MONTH-FRACTION | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1.5},"day":{"type":"number","value":15}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-DAY-ZERO | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":0}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-DAY-NEG1 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":-1}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-DAY-32 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":32}}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-DAY-FRACTION | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"number","value":1.5}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-COMMON-FEB29 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2041},"month":{"type":"number","value":2},"day":{"type":"number","value":29}}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-LEAP-FEB30 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":2},"day":{"type":"number","value":30}}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-APRIL31 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":4},"day":{"type":"number","value":31}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-YEAR-ZERO | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":0},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-YEAR-NEG1 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":-1},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-YEAR-10000 | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":10000},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-FIELD-DM5-YEAR-FRACTION | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040.5},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-FIELD-DM5-YEAR-EMPTY | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"empty-text"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-FIELD-DM5-MONTH-EMPTY | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"empty-text"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-DAY-EMPTY | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"empty-text"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-YEAR-NONNUMERIC | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"text","value":"year"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-MONTH-NONNUMERIC | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"text","value":"month"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-DAY-NONNUMERIC | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"text","value":"day"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-YEAR-ABSENT | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"absent"},"month":{"type":"number","value":1},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-MONTH-ABSENT | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"absent"},"day":{"type":"number","value":1}}} | {"calls":[{"status":"completed","weekday":1,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-FIELD-DM5-DAY-ABSENT | legacy-functional | {"shape":"three named date fields","fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":1},"day":{"type":"absent"}}} | {"calls":[{"status":"completed","weekday":6,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-BASE-ALL | calendar-service | {"shape":"positional fields","field_order":["year","month","day"],"provided":[]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-BASE-AFTER-FIRST | calendar-service | {"shape":"positional fields","field_order":["year","month","day"],"provided":[{"type":"number","value":2040}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-BASE-AFTER-SECOND | calendar-service | {"shape":"positional fields","field_order":["year","month","day"],"provided":[{"type":"number","value":2040},{"type":"number","value":2}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-EXTRA-BASE | calendar-service | {"shape":"positional fields","field_order":["year","month","day"],"provided":[{"type":"number","value":2040},{"type":"number","value":2},{"type":"number","value":29},{"type":"number","value":17}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-MISSING-DM6-ALL | current-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-DM6-AFTER-FIRST | current-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-DM6-AFTER-SECOND | current-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2},{"type":"number","value":29}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-EXTRA-DM6 | current-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2},{"type":"number","value":29},{"type":"number","value":2040},{"type":"number","value":17}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-MISSING-DM5-ALL | legacy-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[]} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-DM5-AFTER-FIRST | legacy-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2}]} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-MISSING-DM5-AFTER-SECOND | legacy-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2},{"type":"number","value":29}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"arithmetic-input diagnostic"}]} |
      | WD-P3-EXTRA-DM5 | legacy-functional | {"shape":"positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":2},{"type":"number","value":29},{"type":"number","value":2040},{"type":"number","value":17}]} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-CARRIER-BASE-OMITTED | calendar-service | {"shape":"omitted date carrier"} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-CARRIER-BASE-UNDEFINED | calendar-service | {"shape":"undefined date carrier"} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-CARRIER-BASE-TEXT | calendar-service | {"shape":"text date carrier"} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-CARRIER-BASE-MAPPING | calendar-service | {"shape":"mapping date carrier"} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-CARRIER-BASE-EXTRA-METHOD-ARG | calendar-service | {"shape":"date collection plus an extra argument","date_fields":{"year":{"type":"number","value":2040},"month":{"type":"number","value":2},"day":{"type":"number","value":29}},"extra_argument":{"type":"text","value":"ignored"}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM6-C20-40 | current-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM6-WINDOW89-40 | current-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"89"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM6-C20-00 | current-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"00"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM6-C19-40 | current-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c19"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C20-00 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"00"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"completed","weekday":3,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C20-40 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C20-99 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"99"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"completed","weekday":7,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C19-40 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c19"}} | {"calls":[{"status":"completed","weekday":5,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C2000-40 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c2000"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-WINDOW89-50 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"50"}],"short_year_rule":{"type":"text","value":"89"}} | {"calls":[{"status":"completed","weekday":2,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-WINDOW89-51 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"51"}],"short_year_rule":{"type":"text","value":"89"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-C-40 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"40"}],"short_year_rule":{"type":"text","value":"c"}} | {"calls":[{"status":"completed","weekday":4,"diagnostic":"none"}]} |
      | WD-P3-SHORT-DM5-LENGTH1-4 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"4"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
      | WD-P3-SHORT-DM5-LENGTH3-040 | legacy-functional | {"shape":"short-year positional fields","field_order":["month","day","year"],"provided":[{"type":"number","value":3},{"type":"number","value":1},{"type":"text","value":"040"}],"short_year_rule":{"type":"text","value":"c20"}} | {"calls":[{"status":"failed","diagnostic":"invalid-input failure"}]} |
