# Original Date::Manip 5.66 compatibility fixture, supplied by the 7.00 distribution.
Language = English
DateFormat = US
WorkWeekBeg = 1
WorkWeekEnd = 5
WorkDayBeg = 09:00
WorkDayEnd = 17:00
WorkDay24Hr = 0
EraseHolidays = 1

*Holidays
Mar 1 = Launch Day
Mar 1 = Audit Day
Mar 2 =

*Events
Mar 1 = All-Day Office Event
2040-03-01 10:00 = One-Hour Briefing
